name: Deploy to one-q.xyz

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      app_name: 'misopin-cms'
      app_port: '3001'
      deploy_path: '/var/www/misopin-cms'
      health_check_url: 'https://cms.one-q.xyz/api/health'
    secrets: inherit
